name: FastAPI CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Run FastAPI app (background)
        run: |
          nohup python book.py &  # Run FastAPI app in the background using `nohup`

      - name: Wait for the FastAPI app to start
        run: |
          # Wait for FastAPI to be up and running
          sleep 5  # Wait for 5 seconds to give FastAPI time to start

      - name: Test FastAPI endpoint
        run: |
          curl -X GET "http://127.0.0.1:8000/books"  # Simple test call to ensure the FastAPI app is running
