name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install pip (if needed)
      - name: Install pip (if needed)
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip

      # Step 4: Create virtual environment and install dependencies
      - name: Create virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install fastapi uvicorn pytest  # Ensure pytest is installed here

      # Step 5: Run FastAPI Tests using pytest
      - name: Run FastAPI Tests
        run: |
          source venv/bin/activate  # Activate virtual environment
          pytest --maxfail=1 --disable-warnings -q  # Run the tests

      # Step 6: Optional - Verify FastAPI installation
      - name: Verify FastAPI installation
        run: |
          source venv/bin/activate
          python3 -c "import fastapi; print('FastAPI installed successfully')"
