name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install pip (if needed)
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip
      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
  
        # Step 4: Install FastAPI in the virtual environment
      - name: Install FastAPI and dependencies
        run: |
          source venv/bin/activate
          pip install fastapi uvicorn
  
        # Step 5: (Optional) Verify installation
      - name: Verify FastAPI installation
        run: |
            source venv/bin/activate
            python3 -c "import fastapi; print('FastAPI installed successfully')"
  
        # Step 6: Run FastAPI application or tests
      - name: Run FastAPI tests
        run: |
          source venv/bin/activate
          pytest
      - name : run the appc
        run : uvicorn book:app --reload