name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      # Step 3: Install dependencies helkdj
      - name : install dependencies
        run : python3 install pip
      
      # Step 4: Run tests
      - name: Run tests
        run: pip install uvicorn

      - name: install the FastAPI environmane
        run : python3 install fastapi-env
      
      - name :  activate
        run  : source fastapienv\bin\activate
      
       
      - name : run the appc
        run : uvicorn book:app --reload