name: FastAPI CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Run FastAPI app (subprocess)
        run: |
          python -c "import subprocess; subprocess.run(['python', 'book.py'], check=True)"  # Runs the FastAPI app using subprocess
          
      - name: Test FastAPI endpoint
        run: |
          curl -X GET "http://127.0.0.1:8002/books"  # Simple test call to ensure the FastAPI app is running
