name: reusablecode
on: 
  workflow_call
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      # Step 3: Install pip and dependencies
      - name: Install pip (if needed)
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip
          pip install uvicorn
          pip install -r requirements.txt

      # Step 4: Create a virtual environment
      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate  # Linux/macOS

      # Step 5: Install FastAPI and dependencies
      - name: Install FastAPI and dependencies
        run: |
          source venv/bin/activate
          pip install fastapi uvicorn

      # Step 6: Upload files to Artifactory
      - name: Upload to Artifactory
        uses: actions/upload-artifact@v4
        with: 
          name: dist files
          path: |
            dist
            package.json

      # Step 7: Verify FastAPI installation
      - name: Verify FastAPI installation
        run: |
          source venv/bin/activate
          python3 -c "import fastapi; print('FastAPI installed successfully')"

      # Step 8: Run the application
      - name: Run application
        run: |
          source venv/bin/activate
          uvicorn book:app --host 0.0.0.0 --port 8000

      # Step 9: Conditional check if the previous step fails
      - name: Conditional check on failure
        if: failure() && steps.send.outcome == 'failure'
        run: |
          sudo apt update

  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to install dependencies (Prometheus instrumentator, etc.)
      - name: Run the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prometheus_fastapi_instrumentator
          pip install -r requirements.txt

      # Step 1: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t my-app .

      # Step 3: Run container
      - name: Run container
        run: docker run -d my-app

      # Step 4: Verify running containers
      - name: Verify container is running
        run: docker ps
      - name: Run Docker container
        run: docker run -d -p 8045:8045 my-app
      