name : reusablecode
on :  workflow_call
jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3
      
            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 2.321.0
      
            # Step 3: Install pip (if needed)
            - name: Install pip (if needed)
              run: |
                python3 -m ensurepip --upgrade
                python3 -m pip install --upgrade pip
      
            # Step 4: Create a virtual environment
            - name: Create virtual environment
              run: |
                python3 -m venv venv
                source venv/bin/activate  # Linux/macOS
      
            # Step 5: Install FastAPI and dependencies
            - name: Install FastAPI and dependencies
              run: |
                source venv/bin/activate
                pip install fastapi uvicorn
      
            # Step 6: Upload files to Artifactory
            - name: Upload to Artifactory
              uses: actions/upload-artifact@v3
              with: 
                name: dist files
                path: |
                  dist
                  package.json
      
            # Step 7: Verify FastAPI installation
            - name: Verify FastAPI installation
              run: |
                  source venv/bin/activate
                  python3 -c "import fastapi; print('FastAPI installed successfully')"
      
            # Step 8: Run the application
            - name: Run application
              #continue-on-error: true
              #id: send
              run: uvicorn book:app --host 0.0.0.0 --port 8000

      
            # Step 9: Conditional  hjasn check if the previous step fails
            - name: Conditional check on failure
              if: failure() && steps.send.outcome == 'failure'  # Use expressions to check step outcome
              run: |
                sudo apt update
    container:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name : run the dependecies 
          run : |
               python -m pip install --upgrade pip       
                pip install prometheus_fastapi_instrumentator
                pip install -r requirements.txt

          
        - name: Build Docker image
          run: docker build -t my-app .
        - name: Run container
          run: docker run my-app